name: "Issue Column Change Label"
on:
  project_card:
    types:
      - moved
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: "remove previous label"
        uses: andymckay/labeler@master
    if: ${{ github.event.project_card.column_id == '19053227' }}
        with:
          add-labels: 'backlog'
          repo-token: ${{ secrets.ACCESS_TOKEN }}
