on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.GH_TOKEN }}"
        project-url: "https://github.com/diopitis/sveltekit-cf-prisma-planetscale/projects/1#column-19053228"
        column-name: "Application Phase"
        label-name: "Initial Review in Progress"
        columns-to-ignore: ""
