on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token:  "${{access_token}}"
        project-url: "https://github.com/vidiabtc/sveltekit-cf-prisma-planetscale/projects/1"
        column-name: "New"
        label-name: "Initial Review in Progress"
        columns-to-ignore: ""
