  - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.GH_TOKEN }}"
        project-url: "https://github.com/stacksgov/grants-dashboard/projects/1"
        column-name: "New"
        label-name: "Initial Review in Progress"
        columns-to-ignore: ""
